spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zrm15070440
    url: jdbc:mysql://localhost:3306/si1v3r
server:
  port: 8080

